name: CI

on:
  push:
    paths:
      - 'apps/**'
  pull_request:
    paths:
      - 'apps/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app:
          - 1_security-context

    defaults:
      run:
        working-directory: apps/${{ matrix.app }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'

      - name: Build binary
        run: go build -o server .

      - name: Run tests
        run: go test ./...

